name: ViperEconomy
author: viper#7429
main: viper\ViperEconomy
version: 1.0.0
api: 3.0.0
description: "New economy system."

# This was coded in like 2 hours :{. Also if you have questions or wanna commit changes message me on discord, viper#7429.
